<?php

/**
 * Implements hook_form_alter().
 */
function validate_session_booking_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "session_node_form") {
    $form['#validate'][] = 'validate_session_booking_form_validate';
  }
}

function validate_session_booking_form_validate($form, &$form_state) {
  // get defaults
  $defaultTime = isset($form['field_schedate'][LANGUAGE_NONE]['#default_value'][0]) ? $form['field_date'][LANGUAGE_NONE]['#default_value'][0] : NULL;
  $defaultRoom = isset($form['field_room'][LANGUAGE_NONE]['#default_value']) ? $form['field_room'][LANGUAGE_NONE]['#default_value'] : NULL;

  // get submitted values
  $time = $form_state['values']['field_schedate'][LANGUAGE_NONE][0]['value'];
  $room = $form_state['values']['field_room'][LANGUAGE_NONE][0]['target_id'];
  if (($defaultTime != $time) || ($defaultRoom != $room)) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'session')
      ->fieldCondition('field_schedate', 'value', $time, '=')
      ->fieldCondition('field_room', 'target_id', $room, '=');

    $result = $query->execute();
    if (isset($result['node'])) {
      form_set_error('field_schedate', t('This room has already been booked for the same time.'));
    }
  }
}